plugins:
  - removeViewBox: false
  - removeDimensions: true
  - cleanupNumericValues:
      floatPrecision: 3
  - mergePaths:
      force: true
  - removeAttrs:
      attrs: '(stroke|fill|clip-rule)'
